In [166]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [167]:
train = pd.read_csv('training_set_features.csv')
train_out = pd.read_csv('training_set_labels.csv')
test = pd.read_csv('test_set_features.csv')

In [168]:
sns.set_style('darkgrid')
matplotlib.rcParams['font.size'] = 14
matplotlib.rcParams['figure.figsize'] = (10, 6)
matplotlib.rcParams['figure.facecolor'] = '#00000000'

In [169]:
train = pd.read_csv('training_set_features.csv')
train = train.merge(train_out[['respondent_id', 'xyz_vaccine']], on='respondent_id', how='left')
train = train.merge(train_out[['respondent_id', 'seasonal_vaccine']], on='respondent_id', how='left')
train

respondent_id  xyz_concern  xyz_knowledge  behavioral_antiviral_meds  \
0                  0          1.0            0.0                        0.0   
1                  1          3.0            2.0                        0.0   
2                  2          1.0            1.0                        0.0   
3                  3          1.0            1.0                        0.0   
4                  4          2.0            1.0                        0.0   
...              ...          ...            ...                        ...   
26702          26702          2.0            0.0                        0.0   
26703          26703          1.0            2.0                        0.0   
26704          26704          2.0            2.0                        0.0   
26705          26705          1.0            1.0                        0.0   
26706          26706          0.0            0.0                        0.0   

       behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                       0.0                   0.0                    0.0   
1                       1.0                   0.0                    1.0   
2                       1.0                   0.0                    0.0   
3                       1.0                   0.0                    1.0   
4                       1.0                   0.0                    1.0   
...                     ...                   ...                    ...   
26702                   1.0                   0.0                    0.0   
26703                   1.0                   0.0                    1.0   
26704                   1.0                   1.0                    1.0   
26705                   0.0                   0.0                    0.0   
26706                   1.0                   0.0                    0.0   

       behavioral_large_gatherings  behavioral_outside_home  \
0                              0.0                      1.0   
1                              0.0                      1.0   
2                              0.0                      0.0   
3                              1.0                      0.0   
4                              1.0                      0.0   
...                            ...                      ...   
26702                          0.0                      1.0   
26703                          0.0                      0.0   
26704                          1.0                      0.0   
26705                          0.0                      0.0   
26706                          0.0                      0.0   

       behavioral_touch_face  ...  rent_or_own   employment_status  \
0                        1.0  ...          Own  Not in Labor Force   
1                        1.0  ...         Rent            Employed   
2                        0.0  ...          Own            Employed   
3                        0.0  ...         Rent  Not in Labor Force   
4                        1.0  ...          Own            Employed   
...                      ...  ...          ...                 ...   
26702                    0.0  ...          Own  Not in Labor Force   
26703                    0.0  ...         Rent            Employed   
26704                    1.0  ...          Own                 NaN   
26705                    NaN  ...         Rent            Employed   
26706                    0.0  ...          Own  Not in Labor Force   

       hhs_geo_region                census_msa  household_adults  \
0            oxchjgsf                   Non-MSA               0.0   
1            bhuqouqj  MSA, Not Principle  City               0.0   
2            qufhixun  MSA, Not Principle  City               2.0   
3            lrircsnp       MSA, Principle City               0.0   
4            qufhixun  MSA, Not Principle  City               1.0   
...               ...                       ...               ...   
26702        qufhixun                   Non-MSA               0.

In [170]:
fig = px.histogram(train, 
                   x='xyz_concern', 
                   color='xyz_vaccine', 
                   color_discrete_sequence=['green', 'grey'])
fig.update_layout(bargap=0.1)
fig.show()

In [171]:
percentage_df = train.groupby('xyz_concern')['xyz_vaccine'].value_counts(normalize = True).mul(100).rename('Percentage').reset_index()
percentage_df

xyz_concern  xyz_vaccine  Percentage
0          0.0            0   86.438107
1          0.0            1   13.561893
2          1.0            0   82.865203
3          1.0            1   17.134797
4          2.0            0   76.614657
5          2.0            1   23.385343
6          3.0            0   70.790677
7          3.0            1   29.209323

In [172]:
MSA_code = {'MSA, Not Principle City': 2, 'MSA, Principle City': 1, 'Non-MSA': 0}
train['MSA_code'] = train.census_msa.map(MSA_code)
train.xyz_vaccine.corr(train.MSA_code)

0.0021421251428088038

In [173]:
sex_code = {'Female': 1, 'Male': 0}
train['sex_code'] = train.sex.map(sex_code)
train.xyz_vaccine.corr(train.sex_code)

0.0206719138483823

In [174]:
corr_df=(train.select_dtypes(include=[np.number])).corr()
new_df = corr_df[corr_df['xyz_vaccine'] >= 0.1]
new_df

respondent_id  xyz_concern  xyz_knowledge  \
xyz_concern                       0.017839     1.000000       0.062522   
xyz_knowledge                     0.003425     0.062522       1.000000   
doctor_recc_xyz                  -0.002072     0.150206       0.093829   
doctor_recc_seasonal              0.001500     0.135567       0.071920   
health_worker                    -0.003149     0.033562       0.170252   
health_insurance                 -0.012603    -0.003655       0.119408   
opinion_xyz_vacc_effective        0.005912     0.239604       0.121009   
opinion_xyz_risk                  0.000958     0.377033       0.073086   
opinion_seas_vacc_effective       0.005935     0.235136       0.086103   
opinion_seas_risk                -0.005291     0.333990       0.076825   
xyz_vaccine                      -0.003280     0.121929       0.117951   
seasonal_vaccine                 -0.004652     0.154828       0.120152   

                             behavioral_antiviral_meds  behavioral_avoidance  \
xyz_concern                                   0.090301              0.233713   
xyz_knowledge                                -0.010836              0.088839   
doctor_recc_xyz                               0.051235              0.068145   
doctor_recc_seasonal                          0.030909              0.074088   
health_worker                                 0.009465              0.001180   
health_insurance                             -0.063988              0.032662   
opinion_xyz_vacc_effective                    0.030211              0.112300   
opinion_xyz_risk                              0.105163              0.117851   
opinion_seas_vacc_effective                   0.015003              0.119554   
opinion_seas_risk                             0.085315              0.129504   
xyz_vaccine                                   0.040608              0.047690   
seasonal_vaccine                              0.006277              0.076395   

                             behavioral_face_mask  behavioral_wash_hands  \
xyz_concern                              0.156032               0.293565   
xyz_knowledge                            0.030050               0.089785   
doctor_recc_xyz                          0.084282               0.088729   
doctor_recc_seasonal                     0.069481               0.102044   
health_worker                            0.069992               0.053761   
health_insurance                        -0.040257               0.031919   
opinion_xyz_vacc_effective               0.037651               0.136987   
opinion_xyz_risk                         0.131165               0.168711   
opinion_seas_vacc_effective              0.041556               0.138517   
opinion_seas_risk                        0.110161               0.172464   
xyz_vaccine                              0.070498               0.074712   
seasonal_vaccine                         0.050083               0.112414   

                             behavioral_large_gatherings  \
xyz_concern                                     0.255031   
xyz_knowledge                                  -0.048898   
doctor_recc_xyz                                 0.082242   
doctor_recc_seasonal                            0.093557   
health_worker                                  -0.032319   
health_insurance                               -0.059000   
opinion_xyz_vacc_effective                      0.052299   
opinion_xyz_risk                                0.126463   
opinion_seas_vacc_effective                     0.078491   
opinion_seas_risk                               0.132865   
xyz_vaccine                                     0.017822   
seasonal_vaccine                                0.064025   

                             behavioral_outside_home  behavioral_touch_face  \
xyz_concern                                 0.246424               0.248016   
xyz_knowledge                              -0.068219               0.086162   
doctor_recc_xyz   

In [175]:
corr_df=(train.select_dtypes(include=[np.number])).corr()
new_df1 = corr_df[corr_df['seasonal_vaccine'] >= 0.1]
new_df1

respondent_id  xyz_concern  xyz_knowledge  \
xyz_concern                       0.017839     1.000000       0.062522   
xyz_knowledge                     0.003425     0.062522       1.000000   
behavioral_wash_hands             0.011105     0.293565       0.089785   
behavioral_touch_face             0.007575     0.248016       0.086162   
doctor_recc_xyz                  -0.002072     0.150206       0.093829   
doctor_recc_seasonal              0.001500     0.135567       0.071920   
chronic_med_condition             0.005797     0.095162      -0.022602   
health_worker                    -0.003149     0.033562       0.170252   
health_insurance                 -0.012603    -0.003655       0.119408   
opinion_xyz_vacc_effective        0.005912     0.239604       0.121009   
opinion_xyz_risk                  0.000958     0.377033       0.073086   
opinion_seas_vacc_effective       0.005935     0.235136       0.086103   
opinion_seas_risk                -0.005291     0.333990       0.076825   
xyz_vaccine                      -0.003280     0.121929       0.117951   
seasonal_vaccine                 -0.004652     0.154828       0.120152   

                             behavioral_antiviral_meds  behavioral_avoidance  \
xyz_concern                                   0.090301              0.233713   
xyz_knowledge                                -0.010836              0.088839   
behavioral_wash_hands                         0.064119              0.338130   
behavioral_touch_face                         0.070868              0.335335   
doctor_recc_xyz                               0.051235              0.068145   
doctor_recc_seasonal                          0.030909              0.074088   
chronic_med_condition                         0.008465              0.039435   
health_worker                                 0.009465              0.001180   
health_insurance                             -0.063988              0.032662   
opinion_xyz_vacc_effective                    0.030211              0.112300   
opinion_xyz_risk                              0.105163              0.117851   
opinion_seas_vacc_effective                   0.015003              0.119554   
opinion_seas_risk                             0.085315              0.129504   
xyz_vaccine                                   0.040608              0.047690   
seasonal_vaccine                              0.006277              0.076395   

                             behavioral_face_mask  behavioral_wash_hands  \
xyz_concern                              0.156032               0.293565   
xyz_knowledge                            0.030050               0.089785   
behavioral_wash_hands                    0.083363               1.000000   
behavioral_touch_face                    0.104335               0.365064   
doctor_recc_xyz                          0.084282               0.088729   
doctor_recc_seasonal                     0.069481               0.102044   
chronic_med_condition                    0.068113               0.030260   
health_worker                            0.069992               0.053761   
health_insurance                        -0.040257               0.031919   
opinion_xyz_vacc_effective               0.037651               0.136987   
opinion_xyz_risk                         0.131165               0.168711   
opinion_seas_vacc_effective              0.041556               0.138517   
opinion_seas_risk                        0.110161               0.172464   
xyz_vaccine                              0.070498               0.074712   
seasonal_vaccine                         0.050083               0.112414   

                             behavioral_large_gatherings  \
xyz_concern                                     0.255031   
xyz_knowledge                                  -0.048898   
behavioral_wash_hands                           0.195364   
behavioral_touch_face                           0.253683   
doctor_recc_xyz                               

In [176]:
relev_cols = ['xyz_concern', 'xyz_knowledge', 'doctor_recc_xyz',
       'doctor_recc_seasonal', 'health_worker', 'health_insurance',
       'opinion_xyz_vacc_effective', 'opinion_xyz_risk',
       'opinion_seas_vacc_effective', 'opinion_seas_risk']

In [186]:
relev_cols1 = ['xyz_concern', 'xyz_knowledge', 'behavioral_wash_hands','behavioral_touch_face','chronic_med_condition', 'doctor_recc_xyz',
       'doctor_recc_seasonal', 'health_worker', 'health_insurance',
       'opinion_xyz_vacc_effective', 'opinion_xyz_risk',
       'opinion_seas_vacc_effective', 'opinion_seas_risk']

In [178]:
train['xyz_concern'] = train['xyz_concern'].fillna(train['xyz_concern'].mean())
train['xyz_knowledge'] = train['xyz_knowledge'].fillna(train['xyz_knowledge'].mean())
train['doctor_recc_xyz'] = train['doctor_recc_xyz'].fillna(train['doctor_recc_xyz'].mean())
train['doctor_recc_seasonal'] = train['doctor_recc_seasonal'].fillna(train['doctor_recc_seasonal'].mean())
train['health_worker'] = train['health_worker'].fillna(train['health_worker'].mean())
train['health_insurance'] = train['health_insurance'].fillna(train['health_insurance'].mean())
train['opinion_xyz_vacc_effective'] = train['opinion_xyz_vacc_effective'].fillna(train['opinion_xyz_vacc_effective'].mean())
train['opinion_xyz_risk'] = train['opinion_xyz_risk'].fillna(train['opinion_xyz_risk'].mean())
train['opinion_seas_vacc_effective'] = train['opinion_seas_vacc_effective'].fillna(train['opinion_seas_vacc_effective'].mean())
train['opinion_seas_risk'] = train['opinion_seas_risk'].fillna(train['opinion_seas_risk'].mean())
train['behavioral_wash_hands'] = train['behavioral_wash_hands'].fillna(train['behavioral_wash_hands'].mean())
train['behavioral_touch_face'] = train['behavioral_touch_face'].fillna(train['behavioral_touch_face'].mean())
train['chronic_med_condition'] = train['chronic_med_condition'].fillna(train['chronic_med_condition'].mean())

In [179]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(train[relev_cols])
scaled_inputs = scaler.transform(train[relev_cols])
scaled_inputs

array([[-0.68060883, -2.04692846, -0.55446235, ..., -1.05205022,
        -1.88095448, -1.25336583],
       [ 1.5202786 ,  1.19564718, -0.55446235, ...,  1.29878405,
        -0.02412569, -0.5243094 ],
       [-0.68060883, -0.42564064,  0.        , ..., -1.05205022,
        -0.02412569, -1.25336583],
       ...,
       [ 0.41983489,  1.19564718, -0.55446235, ...,  1.29878405,
         0.90428871,  0.93380347],
       [-0.68060883, -0.42564064, -0.55446235, ..., -1.05205022,
        -1.88095448, -1.25336583],
       [-1.78105254, -2.04692846, -0.55446235, ..., -1.05205022,
         0.90428871, -1.25336583]])

In [180]:
scaler.fit(train[relev_cols1])
scaled_inputs1 = scaler.transform(train[relev_cols1])
scaled_inputs1

array([[-0.68060883, -2.04692846, -2.17758255, ..., -1.05205022,
        -1.88095448, -1.25336583],
       [ 1.5202786 ,  1.19564718,  0.45994817, ...,  1.29878405,
        -0.02412569, -0.5243094 ],
       [-0.68060883, -0.42564064, -2.17758255, ..., -1.05205022,
        -0.02412569, -1.25336583],
       ...,
       [ 0.41983489,  1.19564718,  0.45994817, ...,  1.29878405,
         0.90428871,  0.93380347],
       [-0.68060883, -0.42564064, -2.17758255, ..., -1.05205022,
        -1.88095448, -1.25336583],
       [-1.78105254, -2.04692846, -2.17758255, ..., -1.05205022,
         0.90428871, -1.25336583]])

In [181]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression().fit(scaled_inputs, train['xyz_vaccine'])
predcitions = model.predict_proba(scaled_inputs)[:,-1]
x = predcitions.astype(float)
x

array([0.02693954, 0.29479856, 0.04495785, ..., 0.24998776, 0.00826819,
       0.13551496])

In [182]:
scaler.fit(test[relev_cols])
scaled_test_inputs = scaler.transform(test[relev_cols])
scaled_test_inputs

array([[ 0.41745753,  1.19225436, -0.53520833, ..., -1.04015821,
         0.90027922, -1.2417622 ],
       [-0.69028411, -0.43216395, -0.53520833, ..., -1.04015821,
        -0.0229254 , -1.2417622 ],
       [ 0.41745753,  1.19225436, -0.53520833, ...,  1.311654  ,
         0.90027922,  0.93844092],
       ...,
       [-1.79802575, -0.43216395, -0.53520833, ...,  0.5277166 ,
        -0.0229254 ,  0.21170655],
       [ 1.52519917, -0.43216395, -0.53520833, ...,  0.5277166 ,
        -0.0229254 ,  0.21170655],
       [ 0.41745753, -0.43216395,  1.86843129, ..., -1.04015821,
         0.90027922,  0.93844092]])

In [183]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
scaled_test_inputs = imputer.fit_transform(scaled_test_inputs)

In [184]:
predcitions2 = model.predict_proba(scaled_test_inputs)[:,-1]
x1 = predcitions2.astype(float)
x1

array([0.1400718 , 0.02600571, 0.38522634, ..., 0.18809234, 0.03820669,
       0.58571759])

In [164]:
model1 = LogisticRegression().fit(scaled_inputs1, train.seasonal_vaccine)
predcitions1 = model1.predict_proba(scaled_inputs1)[:,-1]
y = predcitions1.astype(float)
y

array([0.04871261, 0.18376287, 0.25037855, ..., 0.52399639, 0.01915277,
       0.1905504 ])

In [189]:
scaler.fit(test[relev_cols1])
scaled_test_inputs1 = scaler.transform(test[relev_cols1])
scaled_test_inputs1 = imputer.fit_transform(scaled_test_inputs1)
scaled_test_inputs1

array([[ 0.41745753,  1.19225436,  0.45883667, ..., -1.04015821,
         0.90027922, -1.2417622 ],
       [-0.69028411, -0.43216395, -2.17942474, ..., -1.04015821,
        -0.0229254 , -1.2417622 ],
       [ 0.41745753,  1.19225436,  0.45883667, ...,  1.311654  ,
         0.90027922,  0.93844092],
       ...,
       [-1.79802575, -0.43216395, -2.17942474, ...,  0.5277166 ,
        -0.0229254 ,  0.21170655],
       [ 1.52519917, -0.43216395,  0.45883667, ...,  0.5277166 ,
        -0.0229254 ,  0.21170655],
       [ 0.41745753, -0.43216395,  0.45883667, ..., -1.04015821,
         0.90027922,  0.93844092]])

In [199]:
predcitions3 = model1.predict_proba(scaled_test_inputs1)[:,-1]
y1 = predcitions3.astype(float)
y1

ValueError: X has 15 features, but LogisticRegression is expecting 14 features as input.

In [82]:
import pandas as pd

# Create a dictionary with the data
data = {
   'respondent_id': train['respondent_id'],
   'x': x,
   'y': y
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Save the DataFrame to a CSV file
df.to_csv('data.csv', index=False)

In [160]:
import pandas as pd

# Create a dictionary with the data
data1 = {
   'respondent_id': test['respondent_id'],
   'xyz_vaccine': x1,
   'seasonal_vaccine': y1
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data1)

# Save the DataFrame to a CSV file
df.to_csv('data1.csv', index=False)